### ISSUE TITLE
front view generation with specific input 

### ISSUE THREAD

**Issue by Farewell-ME** [sxl142/TEx-Face#6]
Is it possible to use this work to generate a front view portrait from a side view face image? How can i transfer the input expression to the exp.npy?

**Comment by sxl142** [comment]
1. You can use the inversion model to get the w+ codes of the side view face images and then use the front camera view to render the front face.  2.  You can use Emoca(https://github.com/radekd91/emoca) to extract expression code.

**Comment by Farewell-ME** [comment]
> 1. You can use the inversion model to get the w+ codes of the side view face images and then use the front camera view to render the front face.  2.  You can use Emoca(https://github.com/radekd91/emoca) to extract expression code.

thx! it works~
